name: graph-subscriptions-api Testnet CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    uses: edgeandnode/subscription-payments/.github/workflows/graph-subscriptions-api.template.yml@main
    with:
      APP_NAME: graph-subscriptions-api-arbitrum-goerli
      CLUSTER_NAME: testnet
      CLUSTER_ZONE: us-central1-a
      ENVIRONMENT: arbitrum-goerli
      BASE_IMAGE: ghcr.io/edgeandnode/graph-subscriptions-api
    secrets:
      GCP_GRAPH_NETWORK: ${{ secrets.GCP_GRAPH_NETWORK }}
